### ISSUE TITLE
Select: empty space is present at the top when label is not provided

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#581]
looks similar to #526

![2022-02-01_12-20](https://user-images.githubusercontent.com/2076953/151959704-480b99db-fed9-4893-aabf-57da2065facf.png)

**Comment by fritzSF** [comment]
`<Select
      label='Some Label'
      value='This is some value'
      **labelHidden={true}
      inlineLabel={true}**
      required={false}
      disabled={false}
      invalid={false}
      onChange={(value) => {}}>`

**Comment by fritzSF** [comment]
If you add _labelHidden={true}_ and _inlineLabel={true}_ props, the empty space will disapear.

**Comment by fritzSF** [comment]
Fixed in version  2.4.18

**Comment by tomaskikutis** [comment]
* When `labelHidden` is passed, extra spacing is still present.
* When `labelHidden` is set, spacing disappears, but a part of the label is still visible.
* 

![2022-02-24_16-41](https://user-images.githubusercontent.com/2076953/155559318-2a50dad5-03e5-4bf9-b95a-c5159c2cf5ca.png)

**Comment by fritzSF** [comment]
Well, it actually does. I know it's not very elegant, but we do have a lot of different use cases to cover. Example:  
![Image 2022-03-10 at 12 02 14 [](PM](https://user-images.githubusercontent.com/1861461/157649737-cf7fe5be-29cb-40f6-a5fb-fa3c9e3395b8.png))
In cases like this, where one field has a label and the other one doesn't, we need the space on top to remain. Aligning items differently wouldn't work either because of the info text on the bottom, which can be variable height.
Use case from Planning:
![Image 2022-03-10 at 12 05 23 PM](https://user-images.githubusercontent.com/1861461/157650854-1f093909-f3e2-4cd5-b2d0-c02ef670ea42.png)
I don't have a better solution at the moment, without breaking the quite complex logic.

**Comment by tomaskikutis** [comment]
We could modify `labelHidden` to accept `keepSpacing` property to handle the situation shown in screenshot#1.

```JavaScript
<Select
    label='Some Label'
    value='This is some value'
    labelHidden={{keepSpacing: true}} // <----------------------------------------------
    inlineLabel={true}
    onChange={(value) => { }}
>
```

That's not urgent though, the most important now is fixing the glitch where a part of the label is still visible even if `inlineLabel` and `labelHidden` are both true.

To expand on screenshot#1, alignment wouldn't work in current implementation either if multi-line labels where used. We can't control translations, so we should always support multiple lines where possible, especially in forms where there is no lack of vertical space. To implement it well, a table(or css table) with 2 rows would be needed - one for labels and another one for inputs. Inputs would be separate from labels, but accessibility can be achieved by using `aria-labelledby`. If we implemented it like that, we wouldn't need those empty spaces when label is hidden either :tada:

**Comment by pavlovicnemanja** [comment]
Fixed issue with labels, fix version: v2.4.20. Improvement for keepSpacing is done on beta-3.0.0
